name: Dotnet Library Development Branch Push

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string

    
jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1           
      
      - name: Add nuget source
        run: dotnet nuget add source ${{ secrets.JASGR_NUGET }} -n ${{ secrets.NUGET_NAME }} -u ${{ secrets.NUGET_USER }} -p ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text
      
      - name: Restore Nuget packages
        run: dotnet restore
        
      - name: Build Project
        run: msbuild ${{inputs.repo_name}}.csproj

      - name: dotnet publish 
        run: dotnet publish ${{inputs.repo_name}}.csproj -c release -o snapshot
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{env.repo_name}}
          path: snapshot         
