on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1    
